### PR TITLE
Update build-windows.md

### PR DESCRIPTION
**Pull request by ztjshaha**
Fixed a Typo.

### CODE REVIEW

**Comment by jasonbcox** [comment]
Thanks for the patch. Please open it for review on reviews.bitcoinabc.org
We don't take patches on Github.

**Comment by ztjshaha** [comment]
> Thanks for the patch. Please open it for review on reviews.bitcoinabc.org
> 
> We don't take patches on Github.

gotcha！thanks。

**Comment by Mengerian** [comment]
@ztjshaha I put your patch up for review in Phabricator here: https://reviews.bitcoinabc.org/D8735

**Comment by Mengerian** [comment]
@ztjshaha BTW, it would be good to know if you tested these instructions, so that I can add that info to the testing plan for the Diff.

**Comment by Mengerian** [comment]
Committed here: https://github.com/Bitcoin-ABC/bitcoin-abc/commit/29b1a741de2094a0ce940ce0c250ba5a45fb9ff7

**Pull request closed without merging**
