### PR TITLE
Fixed FreeBSD build instructions

### PR DESCRIPTION
**Pull request by Candunc**
Tested on FreeBSD 11.0-RELEASE

### CODE REVIEW

**Comment by deadalnix** [comment]
Ho Canduc. We are using phabricator for development. See: https://reviews.bitcoinabc.org/

**Comment by Candunc** [comment]
Thanks, I've copied the commit to phabricator and created a differential [here](https://reviews.bitcoinabc.org/D332).

**Comment by deadalnix** [comment]
Thanks.

**Comment by ftrader** [comment]
hi @Candunc 
good work - I have a minor request on D332 on Phabricator. May I ask you to have a look please.
Thanks.

P.S. I'm interested - do you know what it would take to flesh this out to include a GUI build ?

**Pull request closed without merging**
