### PR TITLE
Add hex field to tx object on getblock rpc call

### PR DESCRIPTION
**Pull request by fanatid**
Fixes for #272

### CODE REVIEW

**Comment by jasonbcox** [comment]
Please upload your diff to reviews.bitcoinabc.org so we can put it through our review process. When you do, please note the Bitcoin Core pull request number that's associated with this change if there is one.

Thanks for the PR. :)

**Comment by fanatid** [comment]
I do not see confirmation email from reviews.bitcoinabc.org =(

```diff
diff --git a/src/rpc/blockchain.cpp b/src/rpc/blockchain.cpp
index 05749c3fc..83c978bf5 100644
--- a/src/rpc/blockchain.cpp
+++ b/src/rpc/blockchain.cpp
@@ -12,6 +12,7 @@
 #include "coins.h"
 #include "config.h"
 #include "consensus/validation.h"
+#include "core_io.h"
 #include "hash.h"
 #include "policy/policy.h"
 #include "primitives/transaction.h"
@@ -120,6 +121,7 @@ UniValue blockToJSON(const Config &config, const CBlock &block,
     for (const auto &tx : block.vtx) {
         if (txDetails) {
             UniValue objTx(UniValue::VOBJ);
+            objTx.pushKV("hex", EncodeHexTx(*tx, RPCSerializationFlags()));
             TxToJSON(config, *tx, uint256(), objTx);
             txs.push_back(objTx);
         } else {
```

**Comment by roccomuso** [comment]
@jasonbcox I'm not getting confirmation email too..

**Comment by jasonbcox** [comment]
Sorry, we're having some issue with our email server.  I will get back to you once it's fixed.

**Comment by jasonbcox** [comment]
Sorry, still running into issues with the email server.  In the mean time, I looked into this further.  While your fix will technically work, this isn't the place for the one-liner to live, as it belongs in TxToJSON.  Additionally, there is a backport that appears it will solve this problem as well as help clean up our codebase: https://reviews.bitcoinabc.org/T500 I've assigned it to myself and will target the next release.  I'll also update and close this ticket once the change is in master.

**Pull request closed without merging**
