### PR TITLE
fixed TODO on rpc/blockchain.cpp

### PR DESCRIPTION
**Pull request by gubatron**
regarding a check that should be done in CCoinsViewMemPool, per the TODO comment.

### CODE REVIEW

**Comment by jasonbcox** [comment]
To get proper review on this, please upload your diff to reviews.bitcoinabc.org

**Comment by gubatron** [comment]
I don't get the verification email from Phabricator, nothing on spam.  Will keep trying.
Thank you.

**Comment by jasonbcox** [comment]
Sorry, we're running into some email server issues on Phabricator.  I'll get back to you once they're resolved.

**Comment by gubatron** [comment]
@jasonbcox any chance of getting my account confirmed? still getting this and no emails arrive to my email inbox/spambox
screen shot 2019-01-01 at 6 42 14 pm

**Comment by deadalnix** [comment]
@gubatron email were flacky but should be fixed now. If you did not receive one, immediately after you registered, you should have one by now. Sorry for the inconvenience.

**Comment by gubatron** [comment]
Thanks, I finally got the email, however, I'm having a hard time figuring out Phabricator and how to send my PR there, perhaps it's a permissions issue. I guess a link to Phabricator instructions and how to collaborate there would be helpful.

**Comment by gubatron** [comment]
created a diff over there, I suppose that's how it works in Phabricator
https://reviews.bitcoinabc.org/D2264

**Pull request closed without merging**
