### PR TITLE
addressindex, spentindex, timestampindex (Bitcore patches)

### PR DESCRIPTION
**Pull request by karel-3d**
This is adding indexes (address index etc) necessary for bitcore.

It's code by @braydonf, rebased by me on new bitcoin core, and then rebased by @hanchon on bitcoin-abc (+re-rebased by me on the current master, and I returned the original commit messages)

There is thorough discussion here - https://github.com/bitcoin/bitcoin/pull/10370 - basically, it seems that core is not interested in adding more indexes into the code.

### CODE REVIEW

**Comment by runn1ng** [comment]
not sure what happaned with the one errored build; the rest of the builds went fine

**Comment by hanchon** [comment]
I don't know if it should be committed to master or if it should be committed to a new branch to keep the bitcore code separated. Having it in the master branch makes it seems like bitcoin-abc must have the bitcore new rpc-commands and indexes implemented to run when that is not the case.
The errored build is because the travis had no output for 10min and just timed out.

**Comment by ftrader** [comment]
I'm also in favor of a separate area for the bitcore code.

The failing mingw64 is an issue we are already tracking, definitely unrelated to any of these changes.

**Comment by deadalnix** [comment]
I'm not a big fan of having everything in separated codebases, it causes more work for everybody. But there are obviously various needs in tension here. The indexes for instance is a good one. Many do not want to maintain these indexes, and they probably shouldn't have to.

That being said, the flag -txindex from instance allow to tweak how indexing works. So I don't see why we couldn't do it with bitcore's additions. This will avoid people working on ABC to break bitcore's feature inadvertently and people working on bitcore's features to not have a rebase from hell to do on a regular basis.

That being said this is a HUUUUUGE patch set and it'll be very hard to review in that form, plus the dev going on in other areas might break it. We've adopted a policy were we do small change at once. This essentially allows to go from "there is nothing obviously wrong" to "there is obviously nothing wrong" when doing reviews. I think with should proceed the same with bitcore's additional features.

Final thing, we put our code on github because everybody has an account there, but actually do most of the dev work on phabricator: https://reviews.bitcoinabc.org/ . We should move the code review there.

I lie about that one last thing, there is one more last last thing. We plan to do a fair amount of cleanup after Aug, 1 as there is a ton of logic to handle the UAHF activation that'll become obsolete. That could also simplify what's going on here.

**Comment by runn1ng** [comment]
yep, it's a huge patch set, and I personally cannot vouch for all the code (written mostly by @braydonf, at that time at bitpay, and I just keep rebasing it & testing that it works). But it's also useful. Do what you wish with it

**Comment by deadalnix** [comment]
I would like that someone in the ABC team at least review everything and we integrate it pieces by pieces. That wouldn't be good to have a huge chunk of code in master that nobody understands. I don't think we'll have the manpower to do that before Aug, 1 - for obvious reasons - but I think we should integrate these over time.

**Comment by kleetus** [comment]
FWIW @braydonf is no longer maintaining these indexes in segwit coin code. I am doing what he used to do in this regard and I have decided not to pursue keeping large indexes in bitcoind itself. This is a huge patch and I would not recommend it be considered for inclusion into this code base. Here's why:  

Although these are handy indexes, at the moment, you need to access them via the internal RPC server. Unfortunately, the internal RPC server doesn't scale very well (yes, I realize that it can be made to).  Presumably, requiring these sorts of indexes means you may want to query for the data indexed by them. In real world usage, even with modest loads, the RPCserver becomes over-loaded. Part of the reason for this is the underlying database (leveldb). Leveldb is not really designed to handle many hundreds of gigabytes of data (or more). 

IMHO, I would leave this code out and focus more on the core protocol.

**Comment by schancel** [comment]
I'm closing this pull-request based on staleness.  It's great to maintain these patches, but it does not need to be done as an open pull request.  If these are useful patches for a particular group, I'm happy to advertise another repository where they are maintained.

**Pull request closed without merging**
