### PR TITLE
Grammar correction, hyphen

### PR DESCRIPTION
**Pull request by BitcoinErrorLog**
Grammar correction, hyphen

### CODE REVIEW

**Comment by schancel** [comment]
I've ported your patch over to Phabricator.  Thank you.

https://reviews.bitcoinabc.org/D848

**Comment by BitcoinErrorLog** [comment]
I see my PR was moved to Phabricator and accepted under someone else's name. Will my PR be used here in the gitgub rep, or is my contribution permanently stripped from my identity now?

**Comment by schancel** [comment]
```
commit d85f5425da94790ea8ff2630e26e6b27de4a5ac1 (HEAD -> master, origin/master)
Author: Bitcoin Error Log <bitcoinerrorlog@gmail.com>
Date:   Fri Dec 22 10:08:07 2017 +0200
```

**Comment by schancel** [comment]
Not sure where you got the idea that your identity had been stripped.

**Comment by BitcoinErrorLog** [comment]
Thanks!

**Pull request closed without merging**
