### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by travinkeith**
Minor improvements to the text under "License" to improve the flow.

### CODE REVIEW

**Comment by ftrader** [comment]
I support this change, but we are are working on https://reviews.bitcoinabc.org for all change requests (these only get pushed to github). So we cannot directly merge it here.

@travinkeith , if you would please register an account at the ABC development site which I linked, or let us know if you don't wish to, then we can make this change to the README on your behalf.

**Comment by travinkeith** [comment]
Thanks @josephNLD and @ftrader .

I created an account on reviews.bitcoinabc.org now using my GitHub account, so the username is the same. I tried to go to https://reviews.bitcoinabc.org/source/bitcoin-abc/browse/master/doc/README.md but it seems that I cannot open it in editor myself and create a pull request. My apologies - I'm relatively a noob to Github as well. 

And no problem. Happy to help. :)

**Comment by ftrader** [comment]
@travinkeith : are you able to join btcforks slack via https://btcforks.signup.team/ ?

There are some more setup steps I can assist you with to get your change into ABC.

**Comment by travinkeith** [comment]
@ftrater Sure. I'll try to do that tomorrow. Was a bit sick last week and catching up with things. Need to crash at the moment.

**Comment by schancel** [comment]
@travinkeith are you still active?  I can help you create the patch if you'd like.

**Comment by travinkeith** [comment]
Hi @schancel 

I received further instructions on how to apply it, but got stuck on an endless loop using a Windows machine. I booted up my Linux machine a few weeks ago to try to get it to work (had quite a busy November) but got quite problematic. I should clarify that I'm not much of a developer. 

Since this modification is quite minor, I'm happy to just have the modifications applied directly without a Github-like credit to me. Or is there an easy way about this?

**Comment by schancel** [comment]
@travinkeith Sure, I can do that

**Comment by schancel** [comment]
https://reviews.bitcoinabc.org/D851

**Pull request closed without merging**
